package Interfaz;

import entidades.Carrito;
import entidades.Producto;
import entidades.Pedido;
import negocio.Pedidos;
import negocio.Productos;
import entidades.Usuario;
import java.util.ArrayList;
import java.util.List;
import negocio.TMCarrito;
import servicio.Fecha;

/**
 *
 * @author Equipo2
 */
public class frmCarrito extends javax.swing.JFrame {

    private Carrito carrito;
    private Usuario usuario;
    private TMCarrito modelo;
    private List<Producto> productoLista = new ArrayList<>();
    private float suma = 0.0f;
    private List<Carrito> carritoLista ;
    
    
    /**
     * Constructor de la clase frmCarrito. Inicializa y configura el formulario.
     */
    public frmCarrito() {
        initComponents();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * Método constructor que inicializa la ventana del carrito con el carrito
     * de compra y el usuario que hizo log in
     *
     * @param producto
     * @param usuario el usuario que hizo log in
     */
    public frmCarrito(Carrito carrito, Usuario usuario) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        //productoLista.add(producto);
        this.carrito = carrito;
        this.usuario = usuario;
        Producto producto = null;
        Productos negocioProductos = new Productos();
        
        for (int i = 0; i < this.carrito.getIdProducto().size(); i++) {
            int idProducto = this.carrito.getIdProducto().get(i);
            
            System.out.println("ID del producto: " + idProducto);
            producto = negocioProductos.obtenerProducto(idProducto);
            
            productoLista.add(producto);
            this.suma = this.suma + producto.getPrecio();
        }

        modelo = new TMCarrito(/*carritoLista,*/ productoLista);
        jTable1.setModel(modelo);
        
        campoTextoTotal.setText(String.valueOf(this.suma));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();
        botonPagar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoTextoTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Carrito");

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        botonPagar.setText("Pagar");
        botonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar");

        jLabel1.setText("Total: $");

        campoTextoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volverButton)
                        .addGap(85, 85, 85)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonPagar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoTextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoTextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverButton)
                    .addComponent(botonPagar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_volverButtonActionPerformed

    private void campoTextoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTotalActionPerformed
//        // TODO add your handling code here:
//        for (int i = 0; i < this.carrito.getIdProducto().size(); i++) {
//            int idProducto = this.carrito.getIdProducto().get(i);
//            
//            System.out.println("ID del producto: " + idProducto);
//            producto = negocioProductos.obtenerProducto(idProducto);
//            
//          
//        }
        
    }//GEN-LAST:event_campoTextoTotalActionPerformed

    private void botonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarActionPerformed
        // TODO add your handling code here:
        
        Pedido pedido = new Pedido(new Fecha().toString() , this.suma, this.usuario.getIdUsuario(), this.carrito);
        Pedidos negocioPedido = new Pedidos();
        
        negocioPedido.registrarPedido(pedido);
//        negocioPedido.obtenerPedidos(this.usuario.getIdUsuario());
        this.suma = 0.0f;
        this.setVisible(false);
        System.out.println("pedido registrado");
        this.carrito = null;
    }//GEN-LAST:event_botonPagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPagar;
    private javax.swing.JTextField campoTextoTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
